### ISSUE TITLE
TrustInSoft sample project can't be selected in "Clone repository" dialog

### ISSUE THREAD

**Issue by piec** [TrustInSoft/TrustInSoft#2]
Hi,

The TrustInSoft/TrustInSoft can't be selected in the "Clone repository" dialog.
I suppose your API call which lists github projects filters only C projects and that the project is so small that github doesn't consider TrustInSoft/TrustInSoft as a C project. 

See the language tags:
![image](https://user-images.githubusercontent.com/781471/32330348-256ede04-bfe0-11e7-8328-04006f919796.png)

Cheers

**Comment by Aaylor** [comment]
Hi,

There is actually no filtering made on project language; but your problem is a known bug: the number of GitHub projects we list is limited to a small number. As I can see on your profile, you have more projects than this limitation... This bug is fixed in a version we are currently testing internally, which should be deployed soon.

I will keep you in touch when this bugfix will be deployed.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by Aaylor** [comment]
Hi,

The patch has been released, you're supposed to be able to see all your projects now.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by piec** [comment]
It works thanks
