### ISSUE TITLE
why always when connecting to my analyzer

### ISSUE THREAD

**Issue by aogrcs** [TrustInSoft/TrustInSoft#4]
I signed with my github as the newcomer to analyze crazyflie, but it always had an error

**Comment by Aaylor** [comment]
Hello aorgcs,

The problem you faced was caused by reaching the size limit of your workspace. We have now increased
this limit on your workspace, allowing you to clone and analyze your project.

I took a look at your project, and saw that you do not have a `tis.config` file which is necessary
to run an analysis in Newcomers edition. Ensure you followed the [Newcomers tutorial](https://taas.trust-in-soft.com/images/TIS_Newcomers_Tour_guide.pdf) to
learn how to begin your analysis.


------

An advice on how to start your analysis journey: you can start by analyzing unit test functions as
entry point. I've prodided you an [example](https://taas.trust-in-soft.com/taas/share/2f2efecc138a96405a21247ca168fa2b1493db373ed23435ddd5fde3a0f57277) (clicking on this
link will copy my project into your workspace) which analyze the unit
test function `testThatLimitUint16LimitMax`.

Starting from your [GitHub project](https://github.com/aogrcs/crazyflie-firmware), the first step
is to create a new working branch for TaaS to avoid unwanted changes in other branches:

```
$ git checkout -b taas-newcomers
```

Ensure that all following commands are done on the new branch, in order to avoid the
corruption of your main branch. To continue, you have to delete all submodules (we do 
not support them yet) except `unity`:

```
$ git submodule init vendor/unity && git submodule update vendor/unity
$ git submodule deinit -f -- vendor/{CMSIS,cmock,libdw1000}
$ rm -rf .git/modules/vendor/{CMSIS,cmock,libdw1000,unity}
$ rm -rf vendor/unity/.git
$ mv vendor/unity vendor/unity_tmp
$ git rm -f vendor/{CMSIS,cmock,libdw1000}
```

This will leave your repository in a state where all sources from `CMSIS`, `cmox` and
`libdw1000` (which are not used in this unit test) are totally deleted; and `unity` is 
not a submodule anymore.

```
$ git commit -am 'Delete submodules'
$ mv vendor/unity_tmp vendor/unity
$ git add --all && git commit -am 'Flatten unity'
```

At the project root, write the following `tis.config` and push it:

```javascript
{
    "name": "crazyflies-firmware",
    "files": [
        "test/utils/src/TestNum.c",
        "src/utils/src/num.c",
        "vendor/unity/src/unity.c"
    ],
    "compilation_cmd": "gcc -Isrc/utils/interface -Ivendor/unity/src",
    "main": "testThatLimitUint16LimitMax"
}
```

```
$ git add tis.config
$ git commit -am 'Add tis.config' && git push
```


You can now start you workspace. Click on the button `Clone a GitHub project` (or `Clone repository` if
you already have at least one project), chose the project `crazyflie-firmware` and then `Clone`.

Click on the button `Checkout branch`, chose the project `crazyflie-firmware` and the branch
`taas-newcomers` then click on `Checkout`. The analyzer should start automatically; it should
end in happy ending, telling you that no undefined behavior has been detected.


Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by aogrcs** [comment]
Hi, I did as you suggestion but still got the same error, could you find any other error? Thanks

**Comment by Aaylor** [comment]
Hello aogrcs,

You clicked several times on the link multiple, thus creating as much shared projects. Currently, you have 5 copy which makes you reach the size limit of your workspace again.

Each time you reach the limit size of your workspace, you will get the following page:

![TrustInSoft-Analyzer-Size-Limit](https://image.ibb.co/d1nRKG/Trust_In_Soft_Analyzer_Storage_Limit.png)

This page allows you to clean your workspace by removing the projects that you no longer need. Check the projects you want to delete and click on the Delete button. This action may takes some time.

Thanks for your feedback,
Loïc Runarvot -- TrustInSoft

**Comment by aogrcs** [comment]
Hi
I did not see this page either IE or google chrome! Thanks

**Comment by Aaylor** [comment]
Hi,

There was infact an error that dit not allow you to connect to your workspaces.
You should be able to connect now.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by aogrcs** [comment]
Hi, I can delete them and run the analysis! Thanks for your patient sincerely!
But there is a small problem:
![default](https://user-images.githubusercontent.com/5660925/35252707-9504da96-ffd9-11e7-8c44-bcfa81a36e59.JPG)

**Comment by Aaylor** [comment]
Hello aogrcs,

Have you tried to restart the analyzer (by refreshing the page, or by clicking on the logout button at the top right of the page) ? 

If you already tried, could you please provide:
- the error details (by clicking on the `Show details` button) 
- information given by the `Beta Version` button at the top of the page

The error may not be critical, you can also try to continue to use the analyzer by clicking on the
`Ok` button.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by aogrcs** [comment]
Hi
The error is not critical, I can continue to use the analyzer by clicking on the OK button
The error detail is:
Unexpected error in the 'tis-config-hook' hook while applying the function 'Taas.on_tis_config'.
Uncaught exception: Failure("InvalidStateError") (no backtrace available)

the Beta Version is:
T∙IDE Beta Version (build 7499897f0ab53a87ae910408d8c59ccb2fe9cc67)
For Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

And I could not see the logout button
Thanks, sincerely!

**Comment by Aaylor** [comment]
According to your user-agent, you are using an old version of Internet Explorer (IE11), which is not supported by the TrustInSoft-Analyzer. We are currently supporting only recent version of __Firefox__ and __Google Chrome__. There is no plan to support other web browser for the moment.

We made a test with IE11: it happens that the analyzer is actually opening on the login popup, instead of opening in the main page. Since the popup is small, some part of the layout (the logout button for example) are hidden.

As a workaround, you may take the address of the analyzer, and open it in a tab; this would fix the layout problem, but you'll still have javascript error.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft

**Comment by aogrcs** [comment]
I use Chrome, it is fine now, thanks!
Sincerely

**Comment by aogrcs** [comment]
I think I should close this issue now, thanks!
Sincerely!

**Comment by Aaylor** [comment]
Hello,

I'm glad to here that everything is fine now!
Thanks for closing the issue. Feel free to reopen it, or te create a new one if there is any questions about our services.

Thanks for your feedback,
Loïc Runarvot - TrustInSoft
